export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POSTS_REQUEST = "FETCH_ALL_POSTS_REQUEST";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";

export const FETCH_A_POST_SUCCESS = "FETCH_A_POST_SUCCESS";
export const FETCH_A_POST_REQUEST = "FETCH_A_POST_REQUEST";
export const FETCH_A_POST_FAILURE = "FETCH_A_POST_FAILURE";
